image: openjdk:10.0.1-slim

stages:
  - build
  - test
  - prod

variables:
  SERVICE_NAME: 'java-auth-spring'
  DEPLOY_PATH: '/home/projects/$SERVICE_NAME'
  SERVICE_DIST_FILE_PATH: 'dist/$SERVICE_NAME'

before_script:
  - echo "Before script..."
  - echo "$SSH_PRIVATE_KEY"
  - 'which ssh-agent || ( apt-get update -y && apt-get install git openssh-client -y )'
  - apt-get -y install zip unzip
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

build:
  stage: build
  script:
  - echo "Initiliaze build task..."
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/valandro/java-auth-spring.git
  - cd ./java-auth-spring
  - ./gradlew clean build
  - echo "Finalized build task..."
  artifacts:
    untracked: true
  tags:
    - build

test:
  variables:
    DEPLOY_HOST: 'root@68.183.143.62'
    DEPLOY_PATH: '/home/projects/$SERVICE_NAME'
    DIST_FILE: '$SERVICE_NAME-distribution.jar'
    DOCKER_IMAGE_NAME: '$SERVICE_NAME/java'
  stage: test
  dependencies:
  - build
  script:
  - ssh -o StrictHostKeyChecking=no $DEPLOY_HOST 'exit'
  - ssh $DEPLOY_HOST "rm -rf $DEPLOY_PATH/*"
  - ssh $DEPLOY_HOST "mkdir -p $DEPLOY_PATH/"
  - ssh $DEPLOY_HOST "mkdir -p $SERVICE_DIST_FILE_PATH/"
  - zip -r $DIST_FILE Dockerfile docker-compose.yml $SERVICE_DIST_FILE_PATH/
  - scp $DIST_FILE $DEPLOY_HOST:$DEPLOY_PATH/
  - ssh $DEPLOY_HOST "unzip $DEPLOY_PATH/$DIST_FILE -d $DEPLOY_PATH/"
  - ssh $DEPLOY_HOST "rm $DEPLOY_PATH/$DIST_FILE"
  - echo $DEPLOY_HOST
  - ssh -p 22 $DEPLOY_HOST "docker system prune -f"
  - ssh $DEPLOY_HOST "cd $DEPLOY_PATH/ && docker-compose down && docker-compose up -d --build"
  - echo "Deploy prod finished"