image: openjdk:10.0.1-slim

stages:
  - build
  - test
  - prod

variables:
  SERVICE_NAME: 'java-auth-spring'
  DEPLOY_PATH: '/home/projects/'
  SERVICE_DIST_FILE_PATH: 'build/libs/*.jar'
  APP_PORT: '8090'

before_script:
- 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
- eval $(ssh-agent -s)
- echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
- mkdir -p ~/.ssh
- chmod 700 ~/.ssh
- ./gradlew clean build

build:
  stage: build
  script:
    - echo "Initiliaze build task..."
    - ./gradlew clean build --no-daemon.
    - echo "Finalized build task..."
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - echo "Testing"
    - test -f "build/info.txt"