language: java
jdk:
- openjdk10
matrix:
  include:
  - jdk: openjdk10
    before_install:
    - rm "${JAVA_HOME}/lib/security/cacerts"
    - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
env:
  global:
  - CODECOV_TOKEN="a1f5ebfc-f21f-47cf-a7e2-dc73eb77a8c1"
after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)