language: java
jdk:
- openjdk10
sudo: false
matrix:
  include:
  - jdk: openjdk10
    before_install:
    - rm "${JAVA_HOME}/lib/security/cacerts"
    - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
install:
- true
script:
- "./gradlew --no-daemon --stacktrace -Pcoverage checkstyle check build"
before_install:
- chmod +x gradlew
after_success:
  - ./gradlew codeCoverageReport
  - bash <(curl -s https://codecov.io/bash)
before_cache:
- rm -f  $HOME/.m2
cache:
  directories:
  - $HOME/.m2