install: gradle wrapper --gradle-version 4.2
language: java
jdk:
- openjdk10
matrix:
  include:
  - jdk: openjdk10
    before_install:
    - rm "${JAVA_HOME}/lib/security/cacerts"
    - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

after_success:
  - ./gradlew check codeCoverageReport
  - bash <(curl -s https://codecov.io/bash)