language: java
jdk:
- openjdk10
install:
- true
matrix:
  include:
  - jdk: openjdk10
    before_install:
    - rm "${JAVA_HOME}/lib/security/cacerts"
    - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
before_install:
- chmod +x gradlew
after_success:
  - ./gradlew codeCoverageReport
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - .autoconf
  - $HOME/.m2
before_cache:
- rm -f $HOME/.m2
